### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by JoseJCanedo** [CSU-WebDev/NASA_frontend#20]
https://github.com/CSU-WebDev/NASA_frontend/blob/2b32253bbdf7c220683fc8a8d35ca9da3dbf4d3d/client/public/index.html#L5

Remove comments, use a custom favicon instead of the nasa one

Modify the title, and set it to work with your webpage

**Comment by goodoljosh** [comment]
Completed tasks in this issue except changing the favicon.
